Repository lotteon2/lotdiz-frontend, pull requests merged in 2023-10, with the labels that each got.

#15 feat: add notification page
  .github/workflows/deploy-prod.yml
  public/notification-logo.svg
  public/notification-title-img.svg
  src/assets/css/notification.css
  src/main.ts
  src/router/index.ts
  src/services/api/APISpec.ts
  src/services/api/NotificationService.ts
  src/views/NotificationView.vue
Labels: enhancement

#30 feat: add cors credential
  src/services/api/APISpec.ts
Labels: release

#32 release
  src/assets/css/main.css
  src/assets/css/project-card.css
  src/assets/css/project-list.css
  src/common/HeaderBarComponent.vue
  src/modules/project/components/ProjectCardComponent.vue
  src/services/api/ProjectService.ts
  src/services/types/ProjectResponse.ts
  src/views/LotdealView.vue
  src/views/MainView.vue
  src/views/ProjectListByCategoryView.vue
  src/views/SpecialExhibitionView.vue
Labels: release

#34 release
  src/assets/css/main-project-card.css
  src/modules/project/components/MainLotdealProjectCardComponent.vue
  src/views/MainView.vue
Labels: release

#28 add number of unread notification
  src/assets/css/notification.css
  src/common/.gitkeep
  src/common/HeaderBarComponent.vue
  src/services/api/NotificationService.ts
  src/services/types/NotificationType.ts
Labels: pending
